name: Go

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go (1.20)
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...
